on:
  workflow_dispatch:

jobs:
  create_iwd:
    runs-on: ubuntu-latest
    env:
      REPO_PATH: ${{ github.repository }}
      FOLDER_NAME: ebinmenu
      OUTPUT_FILE_NAME: ebinmenu.iwd
    steps:
      - name: Clone repo
        run: |
          git clone --recurse-submodules "https://github.com/${REPO_PATH}" "${FOLDER_NAME}"

      - name: Unzip existing iwds
        working-directory: ${{ env.FOLDER_NAME }}
        run: unzip *.iwd

      - name: Clean up unnecessary files
        working-directory: ${{ env.FOLDER_NAME }}
        run: |
          rm *.iwd
          rm -r 'bot_warfare/bw-assets'
          find . -type f -name "*.md" -delete
          find . -type f -name "*.png" -delete

      - name: Replace symlinks for bot_warfare
        working-directory: ${{ env.FOLDER_NAME }}
        run: |
          rm 'maps/mp/bots'
          mv 'bot_warfare/maps/mp/bots/' 'maps/mp/'
          rm -r 'bot_warfare/maps/'
          rm 'scriptdata/waypoints'
          mv 'bot_warfare/scriptdata/waypoints/' 'scriptdata/'
          rm -r 'bot_warfare/scriptdata/'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          path: .
