on:
  workflow_dispatch:

jobs:
  create_mod_artifacts:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    env:
      REPO_PATH: ${{ github.repository }}
      FOLDER_NAME: ebinmenu
    steps:
      - name: Clone repo
        run: |
          git clone --recurse-submodules "https://github.com/${REPO_PATH}" "${FOLDER_NAME}"

      - name: Unzip existing iwds
        working-directory: ${{ env.FOLDER_NAME }}
        run: unzip *.iwd

      - name: Clean up unnecessary files
        working-directory: ${{ env.FOLDER_NAME }}
        run: |
          'bot_warfare/bw-assets/' | Remove-Item -Recurse
          '*.iwd', '*.png', '*.md' | Get-ChildItem -Recurse | Remove-Item

      - name: Replace symlinks for bot_warfare
        working-directory: ${{ env.FOLDER_NAME }}
        run: |
          'maps/mp/bots' | Remove-Item
          'bot_warfare/maps/mp/bots/' | Move-Item 'maps/mp/'
          'bot_warfare/maps/' | Remove-Item -Recurse

          'scriptdata/waypoints' | Remove-Item
          'bot_warfare/scriptdata/waypoints/' | Move-Item 'scriptdata/'
          'bot_warfare/scriptdata/' | Remove-Item -Recurse

      - name: Upload UserRaw Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: ebinmenu_userraw
          path: ${{ env.FOLDER_NAME }}

      - name: Upload Mod Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: ebinmenu_mod
          path: .
